[package]
name = "sysmet-notify"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { path = "../../services/log" }
env = { path = "../../services/env" }
metrics = { path = "../../services/metrics", features = ["thresholds"] }

# Parsing command line arguments
clap = { version = "4.0", features = ["derive", "env"] }
clap-verbosity-flag = "2.0"
# Handling errors
eyre = "0.6"
color-eyre = "0.6"
# Sending mails
lettre = { version = "0.10", features = ["builder", "smtp-transport", "hostname", "rustls-tls", "tracing"], default-features = false }
# Handling dates
chrono = { version = "0.4", default-features = false }
# To parse user inputed time
humantime = "2.1"
# Rounding numbers
rust_decimal = "1.26"